name: EmpireEconomy
version: ${project.version}
main: io.github.ellismatthew4.empireeconomy.EmpireEconomy
api-version: 1.16
description: A plugin designed for the upcoming Empire server
commands:
  godmode:
    description: Become invincible.
  emperor:
    description: Assigns the role of emperor.
  balance:
    description: Returns your current bank balance.
  pay:
    description: Gives another player some of your money.
    usage: /pay <target> <amount>
  createmoney:
    description: Prints new money. WARNING - CAN CAUSE INFLATION
    usage: /createmoney <amount>