name: EmpireEconomy
version: ${project.version}
main: io.github.ellismatthew4.empireeconomy.EmpireEconomy
api-version: 1.16
description: A plugin designed for the upcoming Empire server
load: POSTWORLD
commands:
  godmode:
    description: Become invincible.
    permission: ee.*
    permission-message: Only an Administrator can use this command.
  emperor:
    description: Assigns the role of emperor to the user.
    usage: /emperor <PlayerName>
    permission: ee.*
    permission-message: Only an Administrator can use this command.
  balance:
    description: Returns your current bank balance.
  pay:
    description: Gives another player some of your money.
    usage: /pay <target> <amount>
  createmoney:
    description: Prints new money. WARNING - CAN CAUSE INFLATION
    usage: /createmoney <amount>
    permission: ee.emperor
    permission-message: You must be Emperor to use this command.
  challenge:
    description: Issues a challenge to the Emperor, nerfing their powers until you are killed.
  findemperor:
    description: Returns the location of the Emperor.
  wand:
    description: Gives you a Zoning Wand.
  claim:
    description: Claims the area you just zoned out.
    usage: /claim <zone>
  setmessage:
    description: Sets the welcome message for the designated zone.
    usage: /setmessage <zone> <message>
  setzoningrate:
    description: Sets the cost of zoning per block.
    usage: /setzoningrate <cost>
    permission: ee.emperor
    permission-message: You must be Emperor to use this command.
  setsalestax:
    description: Sets the sales tax for the server. [Global]
    usage: /setsalestax <value [0.0 - 1.0]>
    permission: ee.emperor
    permission-message: You must be Emperor to use this command.
  deletezone:
    description: Deletes one of your owned zones.
    usage: /deletezone <zone>
  deletemoney:
    description: Deletes currency from your balance.
    usage: /deletemoney <amount>
    permission: ee.emperor
    permission-message: You must be Emperor to use this command.
  warp:
    description: Teleports you to a Warp Point.
    usage: /warp <player> <name>
  createwarp:
    description: Creates a new Warp Point.
    usage: /createwarp <name> [public|private]
  setwarpcost:
    description: Sets the cost of the designated Warp Point.
    usage: /setwarpcost <name> <cost>
  setdefaultwarpfee:
    description: Sets the default cost of using a Warp Point.
    usage: /setdefaultwarpfee <cost>
    permission-message: You must be Emperor to use this command.
    permission: ee.emperor
  setwarpcreationfee:
    description: Sets the cost to create a Warp Point.
    usage: /setwarpcreationfee <cost>
    permission-message: You must be Emperor to use this command.
    permission: ee.emperor
permissions:
  ee.emperor:
    description: This permission is exclusive for Emperors
    default: false
  ee.*:
    description: Administrator permissions
    default: op