name: EmpireEconomy
version: ${project.version}
main: io.github.ellismatthew4.empireeconomy.EmpireEconomy
api-version: 1.16
description: A plugin designed for managing an Empire server
load: POSTWORLD
commands:
  godmode:
    description: Become invincible.
    permission: ee.*
    permission-message: Only an Administrator can use this command.
  emperor:
    description: Assigns the role of emperor to the user.
    usage: /emperor <PlayerName>
    permission: ee.*
    permission-message: Only an Administrator can use this command.
  balance:
    description: Returns your current bank balance.
  pay:
    description: Gives another player some of your money.
    usage: /pay <target> <amount>
  createmoney:
    description: Prints new money. WARNING - CAN CAUSE INFLATION
    usage: /createmoney <amount>
  challenge:
    description: Issues a challenge to the Emperor, nerfing their powers until you are killed.
  findemperor:
    description: Returns the location of the Emperor.
  wand:
    description: Gives you a Zoning Wand.
  claim:
    description: Claims the area you just zoned out.
    usage: /claim <zone>
  setmessage:
    description: Sets the welcome message for the designated zone.
    usage: /setmessage <zone> <message>
  setzoningrate:
    description: Sets the cost of zoning per block.
    usage: /setzoningrate <cost>
  setsalestax:
    description: Sets the sales tax for the server. [Global]
    usage: /setsalestax <value [0.0 - 1.0]>
  deletezone:
    description: Deletes one of your owned zones.
    usage: /deletezone <zone>
  deletemoney:
    description: Deletes currency from your balance.
    usage: /deletemoney <amount>
  warp:
    description: Teleports you to a Warp Point.
    usage: /warp <player> <name>
  createwarp:
    description: Creates a new Warp Point.
    usage: /createwarp <name> [public|private]
  deletewarp:
    description: Deletes a Warp Point.
    usage: /deletewarp <name>
  setwarpcost:
    description: Sets the cost of the designated Warp Point.
    usage: /setwarpcost <name> <cost>
  setdefaultwarpfee:
    description: Sets the default cost of using a Warp Point.
    usage: /setdefaultwarpfee <cost>
  setwarpcreationfee:
    description: Sets the cost to create a Warp Point.
    usage: /setwarpcreationfee <cost>
  openshop:
    description: Opens a new shop in the current Zone.
    usage: /openshop <name>
  closeshop:
    description: Closes the shop in the current Zone.
    usage: /closeshop
  shop:
    description: Opens the shop in the current Zone.
  list:
    description: Lists the item in your main hand to the shop in the current Zone.
    usage: /list <cost>
  transfer:
    description: Transfers a property to another player.
    usage: /transfer <player> <name>
  writ:
    description: Creates a government-commissioned writ from the held Book and Quill.
    usage: /writ <title>
  punish:
    description: Repossesses all properties owned by the given player.
    usage: /punish <player>
  pardon:
    description: Returns all properties owned by the given player.
    usage: /pardon <player>
  fly:
    description: Toggles flight.
    usage: fly
  vanish:
    description: Toggles invisibility.
    usage: vanish
  properties:
    description: Lists all properties a player owns under a given category.
    usage: /properties <player> [warps|zones|all]
permissions:
  ee.*:
    description: Administrator permissions
    default: op